### ISSUE TITLE
CaseClauseError when watcher detects a new exit

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1235]
@jbunce spotted exceptions after deploying fcb7088 to an environment

```elixir
2019-12-26 06:24:52.110 [info] module=OMG.Watcher.ExitProcessor function=init/1 ⋅Initializing with: {:ok, %OMG.Watcher.ExitProcessor.Core{competitors: %{}, exit_ids: %{2032413964260704897224450687663723715858437494 => {:utxo_position, 1000, 0, 0}}, exits: %{{:utxo_position, 1000, 0, 0} => %OMG.Watcher.ExitProcessor.ExitInfo{amount: 5000000000000000, currency: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, eth_height: 9140291, exit_id: 2032413964260704897224450687663723715858437494, exiting_txbytes: <<248, 178, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 154, 202, 0, 248, 107, ...>>, is_active: true, owner: <<226, 86, 72, 222, 91, 193, 132, 211, 132, 72, 238, 195, 155, 69, 8, 148, 11, 109, 130, 189>>}}, in_flight_exits: %{}, sla_margin: 5520}}⋅

2019-12-26 06:24:52.110 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Starting OMG.EthereumEventListener for exit_processor.⋅

2019-12-26 06:24:52.349 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for exit_processor, synced_height: 9159296⋅

2019-12-26 06:25:01.161 [info] module=OMG.Watcher.ExitProcessor function=handle_call/3 ⋅Recognized exits: [%{call_data: %{output_tx: <<248, 90, 1, 192, 245, 244, 1, 242, 148, 69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, 58, 217, ...>>, utxo_pos: 2002000000000}, eth_height: 9159513, event_signature: "ExitStarted(address,uint160)", exit_id: 832615825608379901973646435154383854844284432, log_index: 28, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<95, 207, 90, 66, 96, 113, 210, 151, 115, 233, 124, 149, 84, 82, 146, 37, 110, 94, 76, 78, 60, 220, 154, 128, 197, 133, 222, 243, 142, 31, 56, 215>>}, %{call_data: %{output_tx: <<248, 123, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 210, 204, 97, 208, 0, 245, 244, 1, 242, 148, 69, 34, 251, 68, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, 58, ...>>, utxo_pos: 16000000000000}, eth_height: 9159947, event_signature: "ExitStarted(address,uint160)", exit_id: 1875022375984755883891285225420292204154037250, log_index: 117, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<166, 99, 126, 59, 158, 6, 30, 150, 5, 68, 26, 213, 136, 48, 211, 29, 181, 50, 67, 191, 161, 182, 57, 148, 189, 199, 122, 78, 131, 86, 0, 112>>}]⋅

2019-12-26 06:25:01.402 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.Watcher.ExitProcessor terminating

** (CaseClauseError) no case clause matching: 2
(ex_abi) lib/abi/type_decoder.ex:258: ABI.TypeDecoder.decode_type/2
(ex_abi) lib/abi/type_decoder.ex:233: anonymous fn/2 in ABI.TypeDecoder.decode_type/2
(elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
(ex_abi) lib/abi/type_decoder.ex:228: ABI.TypeDecoder.decode_type/2
(ex_abi) lib/abi/type_decoder.ex:233: anonymous fn/2 in ABI.TypeDecoder.decode_type/2
(elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
(ex_abi) lib/abi/type_decoder.ex:228: ABI.TypeDecoder.decode_type/2
(ex_abi) lib/abi/type_decoder.ex:222: ABI.TypeDecoder.decode_type/2

Last message (from :exit_processor): {:new_exits, [%{call_data: %{output_tx: <<248, 90, 1, 192, 245, 244, 1, 242, 148, 69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, ...>>, utxo_pos: 2002000000000}, eth_height: 9159513, event_signature: "ExitStarted(address,uint160)", exit_id: 832615825608379901973646435154383854844284432, log_index: 28, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<95, 207, 90, 66, 96, 113, 210, 151, 115, 233, 124, 149, 84, 82, 146, 37, 110, 94, 76, 78, 60, 220, 154, 128, 197, 133, 222, 243, 142, 31, 56, 215>>}, %{call_data: %{output_tx: <<248, 123, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 210, 204, 97, 208, 0, 245, 244, 1, 242, 148, 69, 34, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, ...>>, utxo_pos: 16000000000000}, eth_height: 9159947, event_signature: "ExitStarted(address,uint160)", exit_id: 1875022375984755883891285225420292204154037250, log_index: 117, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<166, 99, 126, 59, 158, 6, 30, 150, 5, 68, 26, 213, 136, 48, 211, 29, 181, 50, 67, 191, 161, 182, 57, 148, 189, 199, 122, 78, 131, 86, 0, 112>>}]}⋅

```

**Comment by unnawut** [comment]
The error also seems to be switching between 

```
** (CaseClauseError) no case clause matching: 4
** (EXIT) an exception was raised:
** (stop) exited in: GenServer.call(OMG.Watcher.ExitProcessor, {:new_exits, [%{call_data: %{output_tx: <<248, 178, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 209, 169, 74, 32, 1, 248, 107, 244, 1, 242, 148, 109, 228, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, ...>>, utxo_pos: 3000000000000}, eth_height: 7011088, event_signature: "ExitStarted(address,uint160)", exit_id: 31695058228720082909122938399884027237980751, log_index: 11, owner: <<109, 228, 179, 185, 194, 142, 156, 62, 132, 194, 178, 211, 168, 117, 201, 71, 168, 77, 230, 141>>, root_chain_txhash: <<19, 253, 128, 95, 42, 88, 14, 42, 144, 156, 228, 157, 179, 226, 76, 132, 105, 116, 36, 203, 176, 67, 96, 56, 207, 23, 192, 147, 203, 54, 54, 196>>}, %{call_data: %{output_tx: <<248, 178, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 186, 125, 239, 48, 1, 248, 107, 244, 1, 242, 148, 109, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, ...>>, utxo_pos: 4000000000000}, eth_height: 7011198, event_signature: "ExitStarted(address,uint160)", exit_id: 44277119116245307650719706943443578846705362, log_index: 5, owner: <<109, 228, 179, 185, 194, 142, 156, 62, 132, 194, 178, 211, 168, 117, 201, 71, 168, 77, 230, 141>>, root_chain_txhash: <<30, 20, 46, 204, 58, 158, 8, 74, 89, 237, 19, 65, 86, 235, 253, 64, 0, 111, 79, 99, 179, 133, 238, 82, 221, 26, 164, 62, 236, 117, 228, 228>>}, %{call_data: %{output_tx: <<248, 178, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 163, 82, 148, 64, 1, 248, 107, 244, 1, 242, 148, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, ...>>, utxo_pos: 5000000000000}, eth_height: 7011265, event_signature: "ExitStarted(address,uint160)", exit_id: 1616494083088678122698853475815062358499933646, log_index: 3, owner: <<109, 228, 179, 185, 194, 142, 156, 62, 132, 194, 178, 211, 168, 117, 201, 71, 168, 77, 230, 141>>, root_chain_txhash: <<193, 121, 103, 1, 103, 1, 130, 228, 16, 206, 204, 93, 242, 99, 116, 45, 115, 224, 145, 77, 79, 2, 5, 21, 152, 101, 108, 180, 147, 71, 204, 98>>}, %{call_data: %{output_tx: <<248, 251, 1, 248, 66, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 212, 165, 16, 1, 160, 0, 0, 0, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, ...>>, utxo_pos: 2000000000000}, eth_height: 7011322, event_signature: "ExitStarted(address,uint160)", exit_id: 2529534946430995132817758747005803201799395141, log_index: 1, owner: <<109, 228, 179, 185, 194, 142, 156, 62, 132, 194, 178, 211, 168, 117, 201, 71, 168, 77, 230, 141>>, root_chain_txhash: <<56, 67, 207, 7, 58, 71, 34, 118, 135, 25, 251, 179, 50, 45, 184, 178, 76, 42, 66, 183, 237, 39, 69, 227, 69, 70, 218, 43, 166, 160, 176, 191>>}]}, 5000)
```

and

```
** (CaseClauseError) no case clause matching: 2
** (EXIT) an exception was raised:
** (stop) exited in: GenServer.call(OMG.Watcher.ExitProcessor, {:new_exits, [%{call_data: %{output_tx: <<248, 90, 1, 192, 245, 244, 1, 242, 148, 69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, 157, ...>>, utxo_pos: 2002000000000}, eth_height: 9159513, event_signature: "ExitStarted(address,uint160)", exit_id: 832615825608379901973646435154383854844284432, log_index: 28, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<95, 207, 90, 66, 96, 113, 210, 151, 115, 233, 124, 149, 84, 82, 146, 37, 110, 94, 76, 78, 60, 220, 154, 128, 197, 133, 222, 243, 142, 31, 56, 215>>}, %{call_data: %{output_tx: <<248, 123, 1, 225, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 210, 204, 97, 208, 0, 245, 244, 1, 242, 148, 69, 34, ...>>, output_tx_inclusion_proof: <<243, 154, 134, 159, 98, 231, 92, 245, 240, 191, 145, 70, 136, 166, 178, 137, 202, 242, 4, 148, 53, 216, 230, 140, 92, 94, 109, 5, 228, 73, 19, 243, 78, 213, 192, 45, 109, 72, 200, 147, 36, 134, 201, ...>>, utxo_pos: 16000000000000}, eth_height: 9159947, event_signature: "ExitStarted(address,uint160)", exit_id: 1875022375984755883891285225420292204154037250, log_index: 117, owner: <<69, 34, 251, 68, 194, 171, 53, 158, 118, 236, 199, 92, 34, 201, 64, 150, 144, 241, 34, 65>>, root_chain_txhash: <<166, 99, 126, 59, 158, 6, 30, 150, 5, 68, 26, 213, 136, 48, 211, 29, 181, 50, 67, 191, 161, 182, 57, 148, 189, 199, 122, 78, 131, 86, 0, 112>>}]}, 5000)
```

**Comment by unnawut** [comment]
Also with @jbunce's help, we can scope down that this started happening somewhere after https://github.com/omisego/elixir-omg/commit/40f899bc32797bc1ff3f286aef2b4c11f586af5c and up to https://github.com/omisego/elixir-omg/commit/fcb7088c02f61abf6a0f195bf8752d08904eb489.

**Comment by unnawut** [comment]
Narrowed down a bit more:

```elixir
iex> {:ok, return} = Ethereumex.HttpClient.eth_call(%{
  to: "0xe687bb4e7e0e1530ee131c4326689e94f84f9cb7",
  data: OMG.Eth.Encoding.to_hex(ABI.encode("standardExits(uint160[])", [[
    832615825608379901973646435154383854844284432, 
    1875022375984755883891285225420292204154037250
  ]]))
})
# {:ok, "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000001d2207fb400ffd216a8fa29d07c6b867153177c43483654c174fcec76b7143fb39c2032cb7c0000000000000000000000004522fb44c2ab359e76ecc75c22c9409690f1224100000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000000031bced02db0000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000e8d4a510000443530dd68f56170ba6fa48a1a0ed644f682b697e34a2a46b839c9fd1c349c2a0000000000000000000000004522fb44c2ab359e76ecc75c22c9409690f1224100000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000000031bced02db0000"}

iex> <<32::size(32)-unit(8), static_array_data::binary>> = OMG.Eth.Encoding.from_hex(return)
# <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>

iex> static_array_data \
  |> ABI.TypeDecoder.decode([
    {:array, {:tuple, [:bool, {:uint, 256}, {:bytes, 32}, :address, {:uint, 256}, {:uint, 256}]},
    Enum.count(exit_ids)}
  ])

** (CaseClauseError) no case clause matching: 2
    lib/abi/type_decoder.ex:258: ABI.TypeDecoder.decode_type/2
    lib/abi/type_decoder.ex:233: anonymous fn/2 in ABI.TypeDecoder.decode_type/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/abi/type_decoder.ex:228: ABI.TypeDecoder.decode_type/2
    lib/abi/type_decoder.ex:233: anonymous fn/2 in ABI.TypeDecoder.decode_type/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/abi/type_decoder.ex:228: ABI.TypeDecoder.decode_type/2
    lib/abi/type_decoder.ex:222: ABI.TypeDecoder.decode_type/2
    lib/abi/type_decoder.ex:173: anonymous fn/2 in ABI.TypeDecoder.do_decode_raw/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/abi/type_decoder.ex:172: ABI.TypeDecoder.do_decode_raw/2
    lib/abi/type_decoder.ex:166: ABI.TypeDecoder.decode_raw/2
```

**Comment by unnawut** [comment]
Found it. The `PaymentStandardExitRouter` contract [returns a variable-length array](https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol#L106), which according to Solidity's [Formal Specification of the Encoding](https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html#formal-specification-of-the-encoding):

> `T[]` where `X` has `k` elements (`k` is assumed to be of type `uint256`):
>
> ```
> enc(X) = enc(k) enc([X[0], ..., X[k-1]])
> ```
> i.e. it is encoded as if it were an array of static size `k`, prefixed with the number of elements.

But our `OMG.Eth.RootChain.get_standard_exits_structs/2` [decodes with the fixed-size array signature](https://github.com/omisego/elixir-omg/blob/master/apps/omg_eth/lib/omg_eth/root_chain.ex#L80):

```elixir
static_array_return_types = [
  {:array, {:tuple, [:bool, {:uint, 256}, {:bytes, 32}, :address, {:uint, 256}, {:uint, 256}]},
  Enum.count(exit_ids)}
]

# ...

ABI.TypeDecoder.decode(..., static_array_return_types)
```

Hence it's picking up `2` and trying to parse into a boolean while in fact `2` is the size of the variable-length array returned.
