### ISSUE TITLE
Internal server error caused by certain IFE tx

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1310]
The following API query returns an internal server error. 

```
POST /in_flight_exit.get_data HTTP/1.1
Content-Type: application/json
host: xxx
Content-Length: 413
Connection: close

{"txbytes":"0xf8b9f843b8418b9e7b949b9b3971074666b9f4814ad3805785612aed4a8f945b71138bcbe16720e8118e52d4e9213a43a0f2079c8ec3296f18af6620adf0a8caff3e9b0d8e4c1b01e1a000000000000000000000000000000000000000000000000000000e8d85ebca00eeed01eb94d42b31665b93c128541c8b89a0e545afb08b7dd89400000000000000000000000000000000000000000180a00000000000000000000000000000000000000000000000000000000000000000","jsonrpc":"2.0","id":0}
```

**Comment by unnawut** [comment]
Also this error is not showing up on sentry.

**Comment by unnawut** [comment]
Backend logs:

```
2020-02-11T07:02:46.772Z,watcher_info,"2020-02-11 07:02:46.771 [info] module=Phoenix.Logger function=phoenix_error_rendered/4 request_id=FfJHEyiMQtcarlgAQabB trace_id=5930791092291909036 span_id=2238661326763052401 ⋅Converted error {:case_clause, {:error, :no_deposit_for_given_blknum}} to 500 response⋅"
2020-02-11T07:02:46.777Z,watcher_info,2020-02-11 07:02:46.776 [error] ⋅#PID<0.17906.15> running OMG.WatcherRPC.Web.Endpoint (cowboy_protocol) terminated
2020-02-11T07:02:46.777Z,watcher_info,Server: audit-6f757ea-watcher-info-ropsten-01.omg.network:80 (http)
2020-02-11T07:02:46.777Z,watcher_info,Request: POST //in_flight_exit.get_data
2020-02-11T07:02:46.777Z,watcher_info,** (exit) an exception was raised:
2020-02-11T07:02:46.777Z,watcher_info,"** (CaseClauseError) no case clause matching: {:error, :no_deposit_for_given_blknum}"
2020-02-11T07:02:46.777Z,watcher_info,(omg_watcher) lib/omg_watcher/api/in_flight_exit.ex:102: OMG.Watcher.API.InFlightExit.find_single_input_data/2
2020-02-11T07:02:46.777Z,watcher_info,(elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
2020-02-11T07:02:46.777Z,watcher_info,(elixir) lib/enum.ex:1990: Enum.reduce_while/3
2020-02-11T07:02:46.777Z,watcher_info,(omg_watcher) lib/omg_watcher/api/in_flight_exit.ex:40: OMG.Watcher.API.InFlightExit.get_in_flight_exit/1
2020-02-11T07:02:46.777Z,watcher_info,(omg_watcher_rpc) lib/web/controllers/in_flight_exit.ex:61: OMG.WatcherRPC.Web.Controller.InFlightExit.handle_txbytes_based_request/4
2020-02-11T07:02:46.777Z,watcher_info,(omg_watcher_rpc) lib/web/controllers/in_flight_exit.ex:15: OMG.WatcherRPC.Web.Controller.InFlightExit.action/2
2020-02-11T07:02:46.777Z,watcher_info,(omg_watcher_rpc) lib/web/controllers/in_flight_exit.ex:15: OMG.WatcherRPC.Web.Controller.InFlightExit.phoenix_controller_pipeline/2
2020-02-11T07:02:46.777Z,watcher_info,(omg_watcher_rpc) lib/web/endpoint.ex:15: OMG.WatcherRPC.Web.Endpoint.instrument/4⋅
```

**Comment by unnawut** [comment]
The watcher info did recognize the deposit on Feb 4:

```elixir
2020-02-04 04:05:49.065 [info] module=OMG.State.Core function=deposit/2 ⋅Recognized deposits [%{amount: 1, blknum: 16001, currency: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, eth_height: 7258385, event_signature: "DepositCreated(address,uint256,address,uint256)", log_index: 5, owner: <<212, 43, 49, 102, 91, 147, 193, 40, 84, 28, 139, 137, 160, 229, 69, 175, 176, 139, 125, 216>>, root_chain_txhash: <<26, 2, 193, 100, 8, 115, 166, 77, 98, 249, 43, 121, 203, 210, 46, 93, 206, 142, 191, 23, 200, 81, 208, 33, 91, 86, 179, 220, 53, 147, 123, 252>>}]⋅
```

And the decoded tx from @thec00n:

```elixir
# RLP decoded tx
 {
  "sigs": [
    "0x8b9e7b949b9b3971074666b9f4814ad3805785612aed4a8f945b71138bcbe16720e8118e52d4e9213a43a0f2079c8ec3296f18af6620adf0a8caff3e9b0d8e4c1b"
  ],
  "txType": 1,
  "inputs": [
    {
      "blknum": 16001,
      "txindex": 0,
      "oindex": 0
    }
  ],
  "outputs": [
    {
      "outputType": 1,
      "outputGuard": "0xd42b31665b93c128541c8b89a0e545afb08b7dd8",
      "currency": "0x0000000000000000000000000000000000000000",
      "amount": "1"
    }
  ],
  "txData": 0,
  "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

**Comment by pdobacz** [comment]
looks similar to https://github.com/omisego/elixir-omg/issues/1128, could it be that you have spent/exited this deposit in some other way?

**Comment by thec00n** [comment]
Could be.

**Comment by pdobacz** [comment]
OK, since the manifestation of the problem is the same as in #1128, let's take the discussion (and labels) there and close this as a duplicate (with high probability at least?).

Unless we can reproduce the problem being sure that the deposit being the input to the IFE **has not been spent or exited yet**.
