### ISSUE TITLE
UndefinedFunctionError: function Mix.env/0 is undefined (module Mix is not available)

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1477]
## Actual behaviour

```
** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
```

## Expected behaviour

`Mix.env()` is not used in runtime code and therefore exception not thrown.

**Comment by unnawut** [comment]
Probably from https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher_info/lib/omg_watcher_info/supervisor.ex#L24-L45

**Comment by unnawut** [comment]
Actually it's from the childchain:

```
:gen_event handler Ink installed in Logger terminating
** (exit) an exception was raised:
** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
Mix.env()
(ink 1.0.3) lib/ink.ex:158: Ink.log_json/2
(ink 1.0.3) lib/ink.ex:97: Ink.handle_event/2
(stdlib 3.12) gen_event.erl:577: :gen_event.server_update/4
(stdlib 3.12) gen_event.erl:559: :gen_event.server_notify/4
(stdlib 3.12) gen_event.erl:300: :gen_event.handle_msg/6
(stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by unnawut** [comment]
Ugh it's from Ink itself: https://github.com/ivx/ink/blob/6f2e9dfdd104b5d8188748767977d5c7f0c06163/lib/ink.ex#L158

**Comment by unnawut** [comment]
It's a cascading failure. Something needs to fail prior for it to reach this condition. Which for this case is https://github.com/omisego/elixir-omg/issues/1478

**Comment by unnawut** [comment]
Pending upstream fix: https://github.com/ivx/ink/pull/57

**Comment by unnawut** [comment]
Upstream updated. I'll take this in a bit.
