### ISSUE TITLE
Sentry.LoggerBackend terminated due to BadMapError

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1478]
```
** (exit) an exception was raised:
** (BadMapError) expected a map, got: [application: :child_chain, eth_network: "ROPSTEN", eth_node: ███, current_version: "vsn-0.4.6+e1f8acf", app_env: "development", hostname: "https://███-childchain-ropsten-███"]
(stdlib 3.12) :maps.merge([application: :child_chain, eth_network: "ROPSTEN", eth_node: ███, current_version: "vsn-0.4.6+e1f8acf", app_env: "development", hostname: "https://███-childchain-ropsten-███"], %{})
(sentry 7.2.3) lib/sentry/event.ex:122: Sentry.Event.create_event/1
(sentry 7.2.3) lib/sentry.ex:126: Sentry.capture_exception/2
(sentry 7.2.3) lib/sentry/logger_backend.ex:93: Sentry.LoggerBackend.handle_event/2
(stdlib 3.12) gen_event.erl:577: :gen_event.server_update/4
(stdlib 3.12) gen_event.erl:559: :gen_event.server_notify/4
(stdlib 3.12) gen_event.erl:300: :gen_event.handle_msg/6
(stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by unnawut** [comment]
Closed by #1489
