### ISSUE TITLE
get_system_memory_data does not have a consistent API

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1484]
http://erlang.org/doc/man/memsup.html#get_system_memory_data-0
For example, this call dies for me because `buffered_memory` is not in the returned keyword.
```
defp get_memory(memsup_module) do
    data = memsup_module.get_system_memory_data()

    %{
      total: Keyword.fetch!(data, :total_memory),
      free: Keyword.fetch!(data, :free_memory),
      buffered: Keyword.fetch!(data, :buffered_memory),
      cached: Keyword.fetch!(data, :cached_memory)
    }
  end
```

```
2020-04-22 16:20:34.991 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.Status.Monitor.MemoryMonitor terminating
** (KeyError) key :buffered_memory not found in: [total_memory: 11294371840, free_memory: 36294656, system_total_memory: 11294371840]
    (elixir 1.10.2) lib/keyword.ex:399: Keyword.fetch!/2
    (omg_status 0.4.6) lib/omg_status/monitor/memory_monitor.ex:136: OMG.Status.Monitor.MemoryMonitor.get_memory/1
    (omg_status 0.4.6) lib/omg_status/monitor/memory_monitor.ex:123: OMG.Status.Monitor.MemoryMonitor.system_memory_exceed_threshold?/2
    (omg_status 0.4.6) lib/omg_status/monitor/memory_monitor.ex:81: OMG.Status.Monitor.MemoryMonitor.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :check⋅
```

**Comment by InoMurko** [comment]
cached_memory as well
```
2020-04-22 16:30:25.468 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.Status.Monitor.MemoryMonitor terminating
** (KeyError) key :cached_memory not found in: [total_memory: 10579968000, free_memory: 19271680, system_total_memory: 10579968000]
    (elixir 1.10.2) lib/keyword.ex:399: Keyword.fetch!/2
    (omg_status 0.4.6) lib/omg_status/monitor/memory_monitor.ex:137: OMG.Status.Monitor.MemoryMonitor.get_memory/1
    (omg_status 0.4.6) lib/omg_status/monitor/memory_monitor.ex:123: OMG.Status.Monitor.MemoryMonitor.system_memory_exceed_threshold?/2
    (omg_status 0.4.6) lib/omg_status/monitor/memory_monitor.ex:81: OMG.Status.Monitor.MemoryMonitor.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :check⋅
```

**Comment by unnawut** [comment]
Hmm, what OS and erlang version are you running on?

**Comment by InoMurko** [comment]
```
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 22)
```
Catalina 10.15.4
