### ISSUE TITLE
Integration tests failure on Mac OS

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#187]
My environment:
* Mac OS High Sierra 10.13.3
* Erlang/OTP 20
* Elixir 1.6.6 (compiled with OTP 19)

How to reproduce:
`mix test --include integration`

Output from test run

#### 1. omg_eth
```
==> omg_eth
Including tags: [:integration, :wrappers]
Excluding tags: [:test, {:wrappers, true}]



  1) test gets events with various fields and topics (OMG.EthTest)
     test/eth_test.exs:76
     ** (MatchError) no match of right hand side value: {:exit_status, 9}
     stacktrace:
       test/support/dev_geth.ex:45: OMG.Eth.DevGeth.stop/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:140: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:126: ExUnit.OnExitHandler.on_exit_runner_loop/0

<more tests failing>

Finished in 114.4 seconds
6 tests, 6 failures
```

#### 2. Happy Path (omg-api) & omg-perftest
```
2018-09-21 12:54:50.657 [error] ⋅GenServer #PID<0.991.0> terminating
** (stop) exited in: GenServer.call(OMG.API.RootChainCoordinator, {:check_in, 14, :depositer}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (omg_api) lib/ethereum_event_listener.ex:87: OMG.API.EthereumEventListener.sync_height/2
    (omg_api) lib/ethereum_event_listener.ex:76: OMG.API.EthereumEventListener.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :sync⋅
2018-09-21 12:54:50.660 [error] ⋅GenServer #PID<0.992.0> terminating
** (stop) exited in: GenServer.call(OMG.API.RootChainCoordinator, {:check_in, 14, :exiter}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (omg_api) lib/ethereum_event_listener.ex:87: OMG.API.EthereumEventListener.sync_height/2
    (omg_api) lib/ethereum_event_listener.ex:76: OMG.API.EthereumEventListener.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :sync⋅
2018-09-21 12:54:53.836 [error] ⋅GenServer OMG.API.RootChainCoordinator terminating
** (MatchError) no match of right hand side value: :invalid_synced_height_update
    (omg_api) lib/root_chain_coordinator/core.ex:64: OMG.API.RootChainCoordinator.Core.check_in/4
    (omg_api) lib/root_chain_coordinator.ex:58: OMG.API.RootChainCoordinator.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.993.0>): {:check_in, 12, :depositer}⋅


  1) test deposit, spend, exit, restart etc works fine (OMG.API.Integration.HappyPathTest)
     test/integration/happy_path_test.exs:33
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:
     
       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry)
     
     Timeouts are given as integers in milliseconds.
     
     stacktrace:
       (elixir) lib/task.ex:491: Task.await/2
       (omg_api) test/support/integration/deposit_helper.ex:56: OMG.API.Integration.DepositHelper.wait_deposit_recognized/1
       (omg_api) test/support/integration/deposit_helper.ex:31: OMG.API.Integration.DepositHelper.deposit_to_child_chain/3
       /Users/pawel/Projects/omisego/apps/omg_api/test/integration/fixtures.exs:60: OMG.API.Integration.Fixtures.fixture_create_alice_deposits/2
       (ex_unit_fixtures) lib/ex_unit_fixtures/imp.ex:154: ExUnitFixtures.Imp.create_fixture/2
       (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ex_unit_fixtures) lib/ex_unit_fixtures/imp.ex:86: ExUnitFixtures.Imp.create_fixtures/4
       (ex_unit_fixtures) lib/ex_unit_fixtures/imp.ex:57: ExUnitFixtures.Imp.test_scoped_fixtures/2
       test/integration/happy_path_test.exs:15: OMG.API.Integration.HappyPathTest.__ex_unit_setup_0/1
       test/integration/happy_path_test.exs:15: OMG.API.Integration.HappyPathTest.__ex_unit__/2
       (ex_unit) lib/ex_unit/runner.ex:299: ExUnit.Runner.exec_test_setup/2
       (ex_unit) lib/ex_unit/runner.ex:246: anonymous fn/2 in ExUnit.Runner.spawn_test/3
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:245: anonymous fn/4 in ExUnit.Runner.spawn_test/3

```

**Comment by InoMurko** [comment]
I have done just been doing this on a clean environment (though on Mojave and no docker) and everything looks fine.

**Comment by pnowosie** [comment]
This issue is outdated and not relevant any more.
We will post an instruction how to setup development env in macos Mojave.

**Comment by pnowosie** [comment]
This issue is outdated and not relevant any more.
We will post an instruction how to setup development env in macos Mojave.
