### ISSUE TITLE
personal_unlockAccount JSON Request encoding breaks Parity compatibility 

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#270]
Parity:

```
2018-11-16 10:59:00 UTC  TRACE rpc  Request: {"params":["ThisIsATestnetPassphrase"],"method":"personal_newAccount","jsonrpc":"2.0","id":0}.
2018-11-16 10:59:00 UTC  DEBUG rpc  [Some(Num(0))] Took 10ms
2018-11-16 10:59:00 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7ee9392ac7a5a0bad08b3943eb9bf8aa4bf02b6f","id":0}.
2018-11-16 10:59:00 UTC  TRACE rpc  Request: {"params":["0x7ee9392ac7a5a0bad08b3943eb9bf8aa4bf02b6f","ThisIsATestnetPassphrase",0],"method":"personal_unlockAccount","jsonrpc":"2.0","id":1}.
2018-11-16 10:59:00 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: integer `0`, expected a 0x-prefixed, hex-encoded number of length 32."},"id":1}.
```

Elixir-omg:

```
mix run --no-start -e  '
   contents = OMG.Eth.DevHelpers.prepare_env!() |> OMG.Eth.DevHelpers.create_conf_file()
   "~/config.exs" |> Path.expand() |> File.write!(contents)
 '
** (MatchError) no match of right hand side value: {:error, %{"code" => -32602, "message" => "Invalid params: invalid type: integer `0`, expected a 0x-prefixed, hex-encoded number of length 32."}}
    test/support/dev_helpers.ex:109: OMG.Eth.DevHelpers.unlock_fund/1
    test/support/dev_helpers.ex:70: OMG.Eth.DevHelpers.create_and_fund_authority_addr/0
    test/support/dev_helpers.ex:44: OMG.Eth.DevHelpers.prepare_env!/1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
    (stdlib) erl_eval.erl:438: :erl_eval.expr/5
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:192: Code.eval_string/3
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (mix) lib/mix/tasks/run.ex:132: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:76: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

`personal_unlockAccount` in https://github.com/omisego/elixir-omg/blob/7949ef4d2892feaa73dd247331cb492d5e12380d/apps/omg_eth/test/support/dev_helpers.ex#L109 is sending a decimal 0 instead of a hex encoded value. This needs to be 0x0 for compatibility with Parity.

https://wiki.parity.io/JSONRPC

**Comment by pdobacz** [comment]
yep, Parity diverges from Geth in `personal`. Thanks!

Note however we're not sure if/when we'll support Parity in `DevHelpers`. If this is the only obstacle, we can just patch, add config var and be happy, but if there's more, we might not want to. (`DevHelpers` is intended to support local development and integration tests)

**Comment by pdobacz** [comment]
#500 #542 #545 have fixed this I presume, since we can run on Parity now, closing
