### ISSUE TITLE
Setry causing exception during error handling

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#437]
Exception thrown in Watcher after responding to invalid request

```
2019-02-12 10:34:37.670 [error] ⋅#PID<0.583.0> running OMG.Watcher.Web.Endpoint (cowboy_protocol) terminated
Server: localhost:7434 (http)
Request: POST /account.get_balance
** (exit) an exception was raised:
    ** (KeyError) key :peer not found in: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %{}, halted: false, host: "localhost", method: "POST", owner: #PID<0.583.0>, params: %{}, path_info: ["account.get_balance"], path_params: %{}, port: 7434, private: %{}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{}, req_headers: [{"content-type", "application/json"}, {"cache-control", "no-cache"}, {"postman-token", "982e2847-c6c3-4ce6-976b-90f1c4ca348d"}, {"user-agent", "PostmanRuntime/7.1.1"}, {"accept", "*/*"}, {"host", "localhost:7434"}, {"accept-encoding", "gzip, deflate"}, {"content-length", "20"}, {"connection", "keep-alive"}], request_path: "/account.get_balance", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}
        lib/sentry/plug.ex:174: Sentry.Plug.build_request_interface_data/2
        (omg_watcher) lib/web/endpoint.ex:15: OMG.Watcher.Web.Endpoint.call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/pnowosie/Proj/omisego/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4⋅
```

Here is [Sentry repo issue](https://github.com/getsentry/sentry-elixir/issues/275). PR was merged, we're probably running older version still.

**Comment by pdobacz** [comment]
in case it offers any help, here's another log dump from a similar issue:

```
Server: watcher.ari.omg.network:80 (http)
Request: POST /account.get_balance/
** (exit) an exception was raised:
    ** (KeyError) key :peer not found in: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %{}, halted: false, host: "watcher.ari.omg.network", method: "POST", owner: #PID<0.21262.0>, params: %{}, path_info: ["account.get_balance"], path_params: %{}, port: 80, private: %{}, query_params: %{}, query_string: "", remote_ip: {10, 148, 15, 250}, req_cookies: %{}, req_headers: [{"host", "watcher.ari.omg.network"}, {"connection", "Keep-Alive"}, {"accept-encoding", "gzip"}, {"cf-ipcountry", "PL"}, {"x-forwarded-for", "5.226.70.4"}, {"cf-ray", "4a9124166a562af7-WAW"}, {"content-length", "99"}, {"x-forwarded-proto", "http"}, {"cf-visitor", "{\"scheme\":\"http\"}"}, {"user-agent", "curl/7.54.0"}, {"accept", "*/*"}, {"content-type", "application/json"}, {"cf-connecting-ip", "5.226.70.4"}, {"cdn-loop", "cloudflare"}], request_path: "/account.get_balance/", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}
        lib/sentry/plug.ex:174: Sentry.Plug.build_request_interface_data/2
        (omg_watcher) lib/web/endpoint.ex:15: OMG.Watcher.Web.Endpoint.call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/elixir-user/elixir-omg/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4⋅
```

**Comment by pdobacz** [comment]
I've bumped `:sentry` to `6.3.0` as suggested. Now I'm getting this:

for a request to Watcher, from iex shell, using httpie:
```
~c(echo '{' | http POST localhost:7434/account.get_utxos) |> :os.cmd()
```

I'm getting:
```
2019-02-20 15:44:05.365 [error] ⋅#PID<0.704.0> running OMG.Watcher.Web.Endpoint (cowboy_protocol) terminated
Server: localhost:7434 (http)
Request: POST /account.get_utxos
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in URI.parse/1
        (elixir) lib/uri.ex:445: URI.parse(nil)
        lib/sentry/client.ex:220: Sentry.Client.get_dsn/0
        lib/sentry/client.ex:323: Sentry.Client.get_headers_and_endpoint/0
        lib/sentry/client.ex:88: Sentry.Client.do_send_event/3
        (omg_watcher) lib/web/endpoint.ex:15: OMG.Watcher.Web.Endpoint.call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/user/sources/omisego/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4⋅
```

(The request has a malformed JSON). I'm not sure whether this is fixed with the update.

I've bumped further to `6.4.2` (`7.0` doesn't start at all), and it is the same.

I've pushed the bumped `mix.exs`/`lock` into a branch `OMG-437_sentry_crashes`, commit referenced above :point_up: 

@jbunce @pnowosie any clues?
