### ISSUE TITLE
status.get breaks if geth is syncing

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#458]
If geth is syncing it returns an object as below, not `true`

**Message**

```
  no case clause matching: {:ok, %{"currentBlock" => "0x3bb704", "highestBlock" => "0x3bb705", "knownStates" => "0x43588f7", "pulledStates" => "0x43588f7", "startingBlock" => "0x3bb704"}}
```

**Backtrace (last 10 lines)**

```
(omg_eth) lib/geth.ex:22: OMG.Eth.Geth.node_ready/0
(omg_eth) lib/geth.ex:36: OMG.Eth.Geth.syncing?/0
(omg_watcher) lib/api/status.ex:54: OMG.Watcher.API.Status.get_status/0
(omg_watcher) lib/web/controllers/status.ex:29: OMG.Watcher.Web.Controller.Status.get_status/2
(omg_watcher) lib/web/controllers/status.ex:15: OMG.Watcher.Web.Controller.Status.action/2
(omg_watcher) lib/web/controllers/status.ex:15: OMG.Watcher.Web.Controller.Status.phoenix_controller_pipeline/2
(omg_watcher) lib/web/endpoint.ex:15: OMG.Watcher.Web.Endpoint.instrument/4
(phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
(omg_watcher) lib/web/endpoint.ex:15: OMG.Watcher.Web.Endpoint.plug_builder_call/2
(omg_watcher) lib/web/endpoint.ex:17: OMG.Watcher.Web.Endpoint."call (overridable 2)"/2
```

`node_ready` is broken. It should allow `syncing?` to just get `true/false` and only break if an explicit error is thrown.

Probably use of `node_ready` in `BlockQueue` and `API.Status` can be cleaned to make more sense.

**Comment by pthomalla** [comment]
fix in commit 658759b8c81ce41bef5b1909041fb3ed6ae3c029
