### ISSUE TITLE
Starting Watcher after fully syncing with 1.5M txs

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#724]
When Watcher starts for the 2nd time after it's fully sync it suffers from several timeouts and UTXO set is loaded several times.

__How to reproduce__
* Feed ch-ch with 1.5M transactions (e.g. for test #723 )
* Sync Watcher, stop it
* Start Watcher again 

[Full log in gist](https://gist.github.com/pnowosie/5df534c92ea7596d75436cf1e3e651c2)

```
2019-05-23 09:23:23.504 [info] module=OMG.DB.LevelDB function=utxos/1 ⋅Reading UTXO set, this might take a while. Allowing 600000 ms⋅
2019-05-23 09:23:52.774 [info] module=OMG.RootChainCoordinator function=handle_continue/2 ⋅Starting Elixir.OMG.RootChainCoordinator service.⋅
2019-05-23 09:23:52.774 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Starting EthereumEventListener for depositor.⋅
2019-05-23 09:23:52.774 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Starting EthereumEventListener for convenience_deposit_processor.⋅
2019-05-23 09:23:52.775 [info] module=OMG.DB.LevelDB function=exit_infos/1 ⋅Reading exits' info, this might take a while. Allowing 60000 ms⋅
2019-05-23 09:23:57.785 [error] module=gen_server function=error_info/7 ⋅GenServer :convenience_deposit_processor terminating
** (stop) exited in: GenServer.call(OMG.DB.LevelDB.Server, {:get_single_value, :last_convenience_deposit_processor_eth_height}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (omg) lib/omg/ethereum_event_listener.ex:71: OMG.EthereumEventListener.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :setup}⋅
2019-05-23 09:23:57.785 [error] module=gen_server function=error_info/7 ⋅GenServer :depositor terminating
** (stop) exited in: GenServer.call(OMG.DB.LevelDB.Server, {:get_single_value, :last_depositor_eth_height}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (omg) lib/omg/ethereum_event_listener.ex:71: OMG.EthereumEventListener.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :setup}⋅
2019-05-23 09:23:57.785 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.State terminating
** (stop) exited in: GenServer.call(OMG.DB.LevelDB.Server, {:get_single_value, :last_deposit_child_blknum}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (omg) lib/omg/state.ex:98: OMG.State.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :setup}⋅

...

2019-05-23 09:25:34.725 [info] module=OMG.DB.LevelDB function=utxos/1 ⋅Reading UTXO set, this might take a while. Allowing 600000 ms⋅
2019-05-23 09:25:50.787 [info] module=OMG.Watcher.ExitProcessor function=init/1 ⋅Initializing with: {:ok, %OMG.Watcher.ExitProcessor.Core{competitors: %{}, exits: %{}, in_flight_exits: %{}, sla_margin: 960}}⋅
2019-05-23 09:25:50.787 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Starting EthereumEventListener for exit_processor.⋅
2019-05-23 09:25:50.787 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Starting EthereumEventListener for convenience_exit_processor.⋅
...
2019-05-23 09:25:50.813 [info] module=Phoenix.Endpoint.CowboyAdapter function=start_link/3 ⋅Running OMG.Watcher.Web.Endpoint with cowboy 1.1.2 at 0.0.0.0:7434 (http)⋅
2019-05-23 09:25:50.818 [info] module=Phoenix.Endpoint.Supervisor function=log_access_info/2 ⋅Access OMG.Watcher.Web.Endpoint at http://localhost:7434⋅
2019-05-23 09:25:55.790 [error] module=gen_server function=error_info/7 ⋅GenServer :exit_processor terminating
** (stop) exited in: GenServer.call(OMG.DB.LevelDB.Server, {:get_single_value, :last_exit_processor_eth_height}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (omg) lib/omg/ethereum_event_listener.ex:71: OMG.EthereumEventListener.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :setup}⋅
2019-05-23 09:25:55.790 [error] module=gen_server function=error_info/7 ⋅GenServer :exit_finalizer terminating
** (stop) exited in: GenServer.call(OMG.DB.LevelDB.Server, {:get_single_value, :last_exit_finalizer_eth_height}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (omg) lib/omg/ethereum_event_listener.ex:71: OMG.EthereumEventListener.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :setup}⋅
2019-05-23 09:25:55.790 [error] module=gen_server function=error_info/7 ⋅GenServer :convenience_exit_processor terminating
** (stop) exited in: GenServer.call(OMG.DB.LevelDB.Server, {:get_single_value, :last_convenience_exit_processor_eth_height}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (omg) lib/omg/ethereum_event_listener.ex:71: OMG.EthereumEventListener.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```

**Comment by pthomalla** [comment]
ExitProcessor started too long, BlockGetter was restarted (did not get a response within 5s)
Restarting BlockGetter entailed State restart.
