### ISSUE TITLE
mix test --include integration doesn't work

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#830]
on 38f47e67c24f9808ffe9962d130756b85730d6b6 it gives a bunch of errors and failed tests, excerpt:

```
Last message: {:error, #PID<0.4518.0>, {Logger, ["GenServer ", "OMG.Watcher.BlockGetter", " terminating", [["\n** (stop) " | "exited in: :sys.get_status(OMG.Watcher.ExitProcessor, 600000)\n    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started"], ["\n    " | "(stdlib) sys.erl:321: :sys.send_system_msg/3"], ["\n    " | "(omg_watcher) lib/omg_watcher/block_getter.ex:78: OMG.Watcher.BlockGetter.handle_continue/2"], ["\n    " | "(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4"], ["\n    " | "(stdlib) gen_server.erl:388: :gen_server.loop/7"], ["\n    " | "(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3"]], "\nLast message", [], ": ", "{:continue, :setup}"], {{2019, 7, 8}, {15, 34, 36, 58}}, [registered_name: OMG.Watcher.BlockGetter, crash_reason: {{:noproc, {:sys, :get_status, [OMG.Watcher.ExitProcessor, 600000]}}, [{:sys, :send_system_msg, 3, [file: 'sys.erl', line: 321]}, {OMG.Watcher.BlockGetter, :handle_continue, 2, [file: 'lib/omg_watcher/block_getter.ex', line: 78]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 388]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, function: "error_info/7", module: :gen_server, line: 888, file: "gen_server.erl", pid: #PID<0.4595.0>]}}⋅
2019-07-08 15:34:36.060 [error] module=gen_server function=error_info/7 ⋅GenServer #PID<0.4596.0> terminating
** (stop) {:EXIT, {:function_clause, [{URI, :parse, [nil], [file: 'lib/uri.ex', line: 445]}, {Sentry.Client, :get_dsn, 0, [file: 'lib/sentry/client.ex', line: 226]}, {Sentry.Client, :get_headers_and_endpoint, 0, [file: 'lib/sentry/client.ex', line: 329]}, {Sentry.Client, :do_send_event, 3, [file: 'lib/sentry/client.ex', line: 92]}, {Sentry.LoggerBackend, :handle_event, 2, [file: 'lib/sentry/logger_backend.ex', line: 38]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
Last message: {:gen_event_EXIT, Sentry.LoggerBackend, {:EXIT, {:function_clause, [{URI, :parse, [nil], [file: 'lib/uri.ex', line: 445]}, {Sentry.Client, :get_dsn, 0, [file: 'lib/sentry/client.ex', line: 226]}, {Sentry.Client, :get_headers_and_endpoint, 0, [file: 'lib/sentry/client.ex', line: 329]}, {Sentry.Client, :do_send_event, 3, [file: 'lib/sentry/client.ex', line: 92]}, {Sentry.LoggerBackend, :handle_event, 2, [file: 'lib/sentry/logger_backend.ex', line: 38]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}⋅
2019-07-08 15:34:56.322 [error] ⋅Task #PID<0.4613.0> started from #PID<0.4424.0> terminating
** (stop) exited in: GenServer.call(OMG.State, :get_status, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (omg_watcher) test/support/integration/test_helper.ex:47: anonymous fn/1 in OMG.Watcher.Integration.TestHelper.wait_for_block_fetch/2
    (omg_eth) lib/omg_eth/wait_for.ex:65: OMG.Eth.WaitFor.repeat_until_ok/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.64281660/0 in OMG.Watcher.Integration.TestHelper.wait_for/2>
    Args: []⋅
2019-07-08 15:34:56.324 [error] module=gen_event function=report_error/5 ⋅:gen_event handler Sentry.LoggerBackend installed in Logger terminating
** (FunctionClauseError) no function clause matching in URI.parse/1
    (elixir) lib/uri.ex:445: URI.parse(nil)
    (sentry) lib/sentry/client.ex:226: Sentry.Client.get_dsn/0
    (sentry) lib/sentry/client.ex:329: Sentry.Client.get_headers_and_endpoint/0
    (sentry) lib/sentry/client.ex:92: Sentry.Client.do_send_event/3
    (sentry) lib/sentry/logger_backend.ex:38: Sentry.LoggerBackend.handle_event/2
    (stdlib) gen_event.erl:577: :gen_event.server_update/4
    (stdlib) gen_event.erl:559: :gen_event.server_notify/4
    (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:error, #PID<0.63.0>, {Logger, ["Task #PID<0.4613.0> started from #PID<0.4424.0> terminating", [["\n** (stop) " | "exited in: GenServer.call(OMG.State, :get_status, 5000)\n    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started"], ["\n    " | "(elixir) lib/gen_server.ex:979: GenServer.call/3"], ["\n    " | "(omg_watcher) test/support/integration/test_helper.ex:47: anonymous fn/1 in OMG.Watcher.Integration.TestHelper.wait_for_block_fetch/2"], ["\n    " | "(omg_eth) lib/omg_eth/wait_for.ex:65: OMG.Eth.WaitFor.repeat_until_ok/1"], ["\n    " | "(elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2"], ["\n    " | "(elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5"], ["\n    " | "(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3"]], "\nFunction: #Function<0.64281660/0 in OMG.Watcher.Integration.TestHelper.wait_for/2>", "\n    Args: []"], {{2019, 7, 8}, {15, 34, 56, 322}}, [crash_reason: {{:noproc, {GenServer, :call, [OMG.State, :get_status, 5000]}}, [{GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 979]}, {OMG.Watcher.Integration.TestHelper, :"-wait_for_block_fetch/2-fun-0-", 1, [file: 'test/support/integration/test_helper.ex', line: 47]}, {OMG.Eth.WaitFor, :repeat_until_ok, 1, [file: 'lib/omg_eth/wait_for.ex', line: 65]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, pid: #PID<0.4613.0>]}}⋅
2019-07-08 15:34:56.325 [error] module=gen_server function=error_info/7 ⋅GenServer #PID<0.4597.0> terminating
** (stop) {:EXIT, {:function_clause, [{URI, :parse, [nil], [file: 'lib/uri.ex', line: 445]}, {Sentry.Client, :get_dsn, 0, [file: 'lib/sentry/client.ex', line: 226]}, {Sentry.Client, :get_headers_and_endpoint, 0, [file: 'lib/sentry/client.ex', line: 329]}, {Sentry.Client, :do_send_event, 3, [file: 'lib/sentry/client.ex', line: 92]}, {Sentry.LoggerBackend, :handle_event, 2, [file: 'lib/sentry/logger_backend.ex', line: 38]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
Last message: {:gen_event_EXIT, Sentry.LoggerBackend, {:EXIT, {:function_clause, [{URI, :parse, [nil], [file: 'lib/uri.ex', line: 445]}, {Sentry.Client, :get_dsn, 0, [file: 'lib/sentry/client.ex', line: 226]}, {Sentry.Client, :get_headers_and_endpoint, 0, [file: 'lib/sentry/client.ex', line: 329]}, {Sentry.Client, :do_send_event, 3, [file: 'lib/sentry/client.ex', line: 92]}, {Sentry.LoggerBackend, :handle_event, 2, [file: 'lib/sentry/logger_backend.ex', line: 38]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}⋅


  3) test in-flight exit competitor is detected by watcher and proven with position immediately (OMG.Watcher.Integration.InFlightExitTest)
     test/omg_watcher/integration/in_flight_exit_test.exs:161
     ** (EXIT from #PID<0.4424.0>) exited in: GenServer.call(OMG.State, :get_status, 5000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started


```

This despite the CI (which splits the tests into subsets) passing fine.

**Comment by InoMurko** [comment]
PR https://github.com/omisego/elixir-omg/pull/884 changes this considerably so maybe wait because #884 might resolve it already...
