### ISSUE TITLE
Watcher's BlockGetter doesn't cover for unexpected structure of the JSON from `block.get`

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#881]
It seems there is an unexpected resonse from the said child chain's endpoint that can confuse the watcher. It would be when the JSON response from that RPC is decoded correctly, but doesn't have the required fields, e.g. is missing the `hash` field.

In such case, `BlockGetter` will go into restarts, because:

```
2019-08-06 12:38:53.537 [error] ⋅Task #PID<0.2395.0> started from OMG.Watcher.BlockGetter terminating
** (FunctionClauseError) no function clause matching in OMG.Watcher.BlockGetter.Core.validate_download_response/5
    (omg_watcher) lib/omg_watcher/block_getter/core.ex:506: OMG.Watcher.BlockGetter.Core.validate_download_response({:ok, %{blknum: 1000, transactions: ["0xf901d2f9010cb8410e4b11e3fde0824d81c7f07daa969b3d1ec1c7a62f91d0c389fb2eb82287b6dd2ef879f786d0065ecea2f22dc6f51c8206d85bd05fda0203f306af7f1c0358631cb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d0c3018080c3808080c3808080c3808080f8b0eb947d6ff7053301d9f2f445560a99ad55664ecc482e94000000000000000000000000000000000000000007eb94dec33023dbd2919f837a51cca1117a3a8329b7c494000000000000000000000000000000000000000003eb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080eb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080"]}}, <<152, 177, 209, 234, 48, 113, 182, 131, 161, 47, 50, 216, 48, 101, 206, 74, 135, 249, 0, 189, 122, 84, 234, 249, 70, 90, 120, 74, 247, 152, 215, 134>>, 1000, 1565087928, 1565087933536)
    (omg_watcher) lib/omg_watcher/block_getter.ex:272: anonymous fn/1 in OMG.Watcher.BlockGetter.run_block_download_task/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<3.38199213/0 in OMG.Watcher.BlockGetter.run_block_download_task/1>
    Args: []⋅
```

Instead it should be treated as either potential `block_withholding` or `invalid_block` (rethink the choice here, considering that garbage JSON leads to `block_withholding` while, things like incorrect (different) hash in a correct JSON structure lead to `invalid_block`).

**Comment by pdobacz** [comment]
note, the client is also unpermissive towards fields that are expected to be hex bineries and but aren't valid hex binaries.

To reproduce, pretend the childchain returns `hash: "hash"` in a block response.
