### ISSUE TITLE
Unable to send tx on plasma-chain

### ISSUE THREAD

**Issue by kendricktan** [omisego/elixir-omg#960]
I've just deployed a fresh set of `plasma-contracts` onto the staging environment using the git sha `f1493aec965bf3072920bc8cf1b281782c148560`.

Things are going fine when I deposit stuff into the plasma chain using [plasma-cli](https://github.com/omisego/plasma-cli)

```bash
./plasma-cli deposit --privatekey="<redacted>" --client="https://rinkeby.infura.io/v3/<redacted>" --contract="0x651f870b62e691204a361fa8b74258ebd40a4620" --amount=10000000 --owner="0xa09E6fB83dbD0bE3CFa03C883F8B2144df1ae
BBC" --currency=""

./plasma-cli get balance --watcher="http://watcher-staging-samrong.omg.network" --address="0xa09E6fB83dbD0bE3CFa03C883F8B2144df1aeBBC"
INFO[2019-09-13T15:05:06+07:00] Starting OmiseGO Plasma MoreVP CLI           
INFO[2019-09-13T15:05:07+07:00] 200 OK                                       
INFO[2019-09-13T15:05:07+07:00] Currency: 0x0000000000000000000000000000000000000000 
INFO[2019-09-13T15:05:07+07:00] Amount: 10000000
```

However, when I try sending, it immediately fails:
```bash
./plasma-cli send --to="<redacted>" --privatekey="<redacted>" --watcher="http://watcher-staging-samrong.omg.network" --amount="80085"

INFO[2019-09-13T15:05:34+07:00] Starting OmiseGO Plasma MoreVP CLI           
WARN[2019-09-13T15:05:35+07:00] Could not unmarshal successful response from the Watcher 
FATA[2019-09-13T15:05:35+07:00] Unknown response from Watcher API 
```

Logs from the watcher:
```log
2019-09-13 07:58:31.343 [error] module=OMG.WatcherRPC.Web.Views.Error function=template_not_found/2 request_id=FcPwfCn2WP1quu4AAAeB trace_id=907279509839850217 span_id=5534822269374479312 ⋅Unhandled error occurred most likely in controller / API layer: %{__phx_template_not_found__: OMG.WatcherRPC.Web.Views.Error, conn: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{kind: :error, layout: false, reason: %Protocol.UndefinedError{description: "Jason.Encoder protocol must always be explicitly implemented", protocol: Jason.Encoder, value: {:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}}, stack: [{Jason, :encode_to_iodata!, 2, [file: 'lib/jason.ex', line: 199]}, {Phoenix.Controller, :json, 2, [file: 'lib/phoenix/controller.ex', line: 279]}, {OMG.WatcherRPC.Web.Controller.Transaction, :action, 2, [file: 'lib/web/controllers/transaction.ex', line: 15]}, {OMG.WatcherRPC.Web.Controller.Transaction, :phoenix_controller_pipeline, 2, [file: 'lib/web/controllers/transaction.ex', line: 15]}, {OMG.WatcherRPC.Web.Endpoint, :instrument, 4, [file: 'lib/web/endpoint.ex', line: 15]}, {OMG.WatcherRPC.Web.Controller.Transaction, :call, 2, [file: 'lib/spandex_phoenix.ex', line: 156]}, {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 280]}, {OMG.WatcherRPC.Web.Endpoint, :plug_builder_call, 2, [file: 'lib/web/endpoint.ex', line: 15]}]}, before_send: [#Function<1.112466771/1 in Plug.Logger.call/2>], body_params: %{"WatcherEndpoint" => "http://watcher-staging-samrong.omg.network", "domain" => %{"name" => "OMG Network", "salt" => "0xfad5c7f626d80f9256ef01929f3beb96e058b8b4b0e3fe52d84f054c0e2a7a83", "verifyingContract" => "0x651f870b62e691204a361fa8b74258ebd40a4620", "version" => "1"}, "message" => %{"input0" => %{"blknum" => 1, "oindex" => 0, "txindex" => 0}, "input1" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0}, "input2" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0}, "input3" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0}, "metadata" => "0x0000000000000000000000000000000000000000000000000000000000000000", "output0" => %{"amount" => 80085, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0x12a4f6ee4ccbd1d0031297293ba9dc26a3ec3999"}, "output1" => %{"amount" => 9919915, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0xa09e6fb83dbd0be3cfa03c883f8b2144df1aebbc"}, "output2" => %{"amount" => 0, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0x0000000000000000000000000000000000000000"}, "output3" => %{"amount" => 0, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0x0000000000000000000000000000000000000000"}}, "signatures" => ["0x92d6ed759dc74e64b509675acb3de73f308921a4f4a5982089ec19d30a36945b701d6087b3b651621523e5ff523192324a9dd6fdf4773b3dd122aa306cd063e41c"]}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "watcher-staging-samrong.omg.network", method: "POST", owner: #PID<0.5086.0>, params: %{"WatcherEndpoint" => "http://watcher-staging-samrong.omg.network", "domain" => %{"name" => "OMG Network", "salt" => "0xfad5c7f626d80f9256ef01929f3beb96e058b8b4b0e3fe52d84f054c0e2a7a83", "verifyingContract" => "0x651f870b62e691204a361fa8b74258ebd40a4620", "version" => "1"}, "message" => %{"input0" => %{"blknum" => 1, "oindex" => 0, "txindex" => 0}, "input1" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0}, "input2" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0}, "input3" => %{"blknum" => 0, "oindex" => 0, "txindex" => 0}, "metadata" => "0x0000000000000000000000000000000000000000000000000000000000000000", "output0" => %{"amount" => 80085, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0x12a4f6ee4ccbd1d0031297293ba9dc26a3ec3999"}, "output1" => %{"amount" => 9919915, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0xa09e6fb83dbd0be3cfa03c883f8b2144df1aebbc"}, "output2" => %{"amount" => 0, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0x0000000000000000000000000000000000000000"}, "output3" => %{"amount" => 0, "currency" => "0x0000000000000000000000000000000000000000", "owner" => "0x0000000000000000000000000000000000000000"}}, "signatures" => ["0x92d6ed759dc74e64b509675acb3de73f308921a4f4a5982089ec19d30a36945b701d6087b3b651621523e5ff523192324a9dd6fdf4773b3dd122aa306cd063e41c"]}, path_info: ["transaction.submit_typed"], path_params: %{}, port: 80, private: %{OMG.WatcherRPC.Web.Router => {[], %{}}, :phoenix_endpoint => OMG.WatcherRPC.Web.Endpoint, :phoenix_format => "json", :phoenix_layout => false, :phoenix_router => OMG.WatcherRPC.Web.Router, :phoenix_template => "500.json", :phoenix_view => OMG.WatcherRPC.Web.Views.Error}, query_params: %{}, query_string: "", remote_ip: {0, 0, 0, 0, 0, 65535, 2708, 106}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "watcher-staging-samrong.omg.network"}, {"accept-encoding", "gzip"}, {"cf-ipcountry", "TH"}, {"cf-ray", "51589395bfa1ddbf-SIN"}, {"content-length", "1211"}, {"x-forwarded-proto", "http"}, {"cf-visitor", "{\"scheme\":\"http\"}"}, {"user-agent", "Go-http-client/1.1"}, {"content-type", "application/json"}, {"cf-connecting-ip", "49.229.255.251"}, {"cdn-loop", "cloudflare"}, {"x-cloud-trace-context", "e4dad169c4d81a608f8621e06ef31f6f/2716276988454258096"}, {"via", "1.1 google"}, {"x-forwarded-for", "49.229.255.251, 162.158.166.19, 34.96.89.226"}, {"connection", "Keep-Alive"}], request_path: "/transaction.submit_typed", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "FcPwfCn2WP1quu4AAAeB"}, {"access-control-allow-origin", "*"}, {"access-control-expose-headers", ""}, {"access-control-allow-credentials", "true"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: 500}, kind: :error, reason: %Protocol.UndefinedError{description: "Jason.Encoder protocol must always be explicitly implemented", protocol: Jason.Encoder, value: {:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}}, stack: [{Jason, :encode_to_iodata!, 2, [file: 'lib/jason.ex', line: 199]}, {Phoenix.Controller, :json, 2, [file: 'lib/phoenix/controller.ex', line: 279]}, {OMG.WatcherRPC.Web.Controller.Transaction, :action, 2, [file: 'lib/web/controllers/transaction.ex', line: 15]}, {OMG.WatcherRPC.Web.Controller.Transaction, :phoenix_controller_pipeline, 2, [file: 'lib/web/controllers/transaction.ex', line: 15]}, {OMG.WatcherRPC.Web.Endpoint, :instrument, 4, [file: 'lib/web/endpoint.ex', line: 15]}, {OMG.WatcherRPC.Web.Controller.Transaction, :call, 2, [file: 'lib/spandex_phoenix.ex', line: 156]}, {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 280]}, {OMG.WatcherRPC.Web.Endpoint, :plug_builder_call, 2, [file: 'lib/web/endpoint.ex', line: 15]}], view_module: OMG.WatcherRPC.Web.Views.Error, view_template: "500.json"}⋅
2019-09-13 07:58:31.343 [info] module=Phoenix.Logger function=phoenix_error_rendered/4 request_id=FcPwfCn2WP1quu4AAAeB trace_id=907279509839850217 span_id=5534822269374479312 ⋅Converted error Protocol.UndefinedError to 500 response⋅
2019-09-13 07:58:31.345 [error] ⋅#PID<0.5086.0> running OMG.WatcherRPC.Web.Endpoint (cowboy_protocol) terminated
Server: watcher-staging-samrong.omg.network:80 (http)
Request: POST /transaction.submit_typed
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: {:nocatch, "Unmatched render clause for template \"<unable to find>\" in \"<unable to find>\""}
        (omg_watcher_rpc) lib/web/views/error.ex:57: OMG.WatcherRPC.Web.Views.Error.template_not_found/2
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix) lib/phoenix/endpoint/render_errors.ex:77: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
        (phoenix) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
        (omg_watcher_rpc) lib/web/endpoint.ex:15: OMG.WatcherRPC.Web.Endpoint.call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4⋅
```

**Comment by pnowosie** [comment]
Note: seems that client lib uses new `/transaction.submit_typed` endpoint. We have a test for it [here](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher/test/omg_watcher/integration/transaction_submit_test.exs)
I'm suspecting the request's parameter caused validation to crash, probably due to incorrect transaction. It would be great to know what was the request body.

**Comment by kendricktan** [comment]
I have a suspicion that this issue arises when the watcher has a misconfigured childchain URL

**Comment by InoMurko** [comment]
Development has been resurrected and is fully functional.
Staging needs to match production, that part we need to work on still -> @kendricktan 

@jrhite are you up to writing a short one what were the issues with postgres and how you fixed it?

**Comment by kasima** [comment]
> Development has been resurrected and is fully functional.

Almost. We're seeing connection errors from the datadog-agent. Looking into it now. Will link to an Issue.

> Staging needs to match production, that part we need to work on still -> @kendricktan

We're going to work on staging once we get development fully healthy.

**Comment by jrhite** [comment]
@InoMurko actually I didn't do anything. I let the pros @kendricktan and @kasima handle it. 😄 

My understanding is what happened was Childchain's rocks/leveldb had been wiped. A new contract had been deployed. Childchain and Watcher had been redeployed. **But** postgres data was not deleted.

When seeing the big picture like that it's easy to see that `txouputs - unique constraint` violations would occur.

@kendricktan - when all the fires are out, can you please write up a post-mortem on all this? Nothing fancy, just something that will help us avoid this happening again.

**Comment by kendricktan** [comment]
@jrhite Sure, I'll do it first thing Monday morning
