### ISSUE TITLE
Migrations fail on deployed development Watcher

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#966]
```
Running migration for OMG.Watcher.DB.Repo...
2019-09-13 15:25:19.212 [info] module=Ecto.Migration.Runner function=log/2 ⋅== Running 20190806111817 OMG.Watcher.DB.Repo.Migrations.AlterTxOutputsTableAddRootchainTxnHashDepositAndExitColumns.up/0 forward⋅
2019-09-13 15:25:19.214 [info] module=Ecto.Migration.Runner function=log/2 ⋅drop constraint txoutputs_creating_deposit_fkey from table txoutputs⋅
2019-09-13 15:25:19.216 [info] module=Ecto.Migration.Runner function=log/2 ⋅drop constraint txoutputs_spending_exit_fkey from table txoutputs⋅
2019-09-13 15:25:19.218 [info] module=Ecto.Migration.Runner function=log/2 ⋅drop constraint ethevents_pkey from table ethevents⋅
2019-09-13 15:25:19.220 [info] module=Ecto.Migration.Runner function=log/2 ⋅drop table ethevents⋅
2019-09-13 15:25:19.221 [info] module=Ecto.Migration.Runner function=log/2 ⋅create table ethevents⋅
2019-09-13 15:25:19.230 [info] module=Ecto.Migration.Runner function=log/2 ⋅create index ethevents_root_chain_txhash_index⋅
2019-09-13 15:25:19.234 [info] module=Ecto.Migration.Runner function=log/2 ⋅create index ethevents_log_index_index⋅
2019-09-13 15:25:19.238 [info] module=Ecto.Migration.Runner function=log/2 ⋅create index ethevents_root_chain_txhash_event_index⋅
2019-09-13 15:25:19.243 [info] module=Ecto.Migration.Runner function=log/2 ⋅execute "ALTER TABLE ethevents ALTER COLUMN inserted_at SET DEFAULT (now() at time zone 'utc');"⋅
2019-09-13 15:25:19.246 [info] module=Ecto.Migration.Runner function=log/2 ⋅execute "ALTER TABLE ethevents ALTER COLUMN updated_at SET DEFAULT (now() at time zone 'utc');"⋅
2019-09-13 15:25:19.247 [info] module=Ecto.Migration.Runner function=log/2 ⋅alter table txoutputs⋅
2019-09-13 15:25:19.248 [info] module=Ecto.Migration.Runner function=log/2 ⋅create index txoutputs_child_chain_utxohash_index⋅
2019-09-13 15:25:19.256 [info] module=Ecto.Migration.Runner function=log/2 ⋅execute "  UPDATE txoutputs as t\n    SET child_chain_utxohash =\n      (SELECT\n         CASE WHEN creating_deposit IS NULL THEN spending_exit\n              WHEN spending_exit IS NULL THEN creating_deposit\n              ELSE creating_deposit || spending_exit\n         END AS txhash\n       FROM txoutputs as t_inner\n       WHERE t.creating_deposit = t_inner.creating_deposit OR t.spending_exit = t_inner.spending_exit);\n"⋅
2019-09-13 15:25:19.343 [info] module=Ecto.Migration.Runner function=log/2 ⋅alter table txoutputs⋅
▸  Evaluation failed with: ERROR 23502 (not_null_violation) column "inserted_at" contains null values
▸      table: txoutputs
▸      column: inserted_at
▸      (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
▸      (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
▸      (ecto_sql) lib/ecto/adapters/sql.ex:705: Ecto.Adapters.SQL.execute_ddl/4
▸      (ecto_sql) lib/ecto/migration/runner.ex:302: Ecto.Migration.Runner.log_and_execute_ddl/3
▸      (ecto_sql) lib/ecto/migration/runner.ex:111: anonymous fn/5 in Ecto.Migration.Runner.flush/0
▸      (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
▸      (ecto_sql) lib/ecto/migration/runner.ex:110: Ecto.Migration.Runner.flush/0
▸      (stdlib) timer.erl:166: :timer.tc/1
```

**Comment by jrhite** [comment]
@InoMurko I can fix this my removing the `not null` constraint. That's fine for dev. When we move to mainnet and true production where we shouldn't have any rows yet, I think we should put the `not null` constraint back in.

Thoughts?
